{
  "ticket": {
    "iteration": 111,
    "pkg": "connman-1.40",
    "affected": {
      "CVE-2022-23098": {
        "branches": [
          {
            "name": "nixos-21.11",
            "rev": "2128d0aa28edef51fd8fef38b132ffc0155595df"
          },
          {
            "name": "nixos-unstable",
            "rev": "5aaed40d22f0d9376330b6fa413223435ad6fee5"
          }
        ],
        "score": 7.5,
        "description": "An issue was discovered in the DNS proxy in Connman through 1.40. The TCP server reply implementation has an infinite loop if no data is received."
      },
      "CVE-2022-23097": {
        "branches": [
          {
            "name": "nixos-21.11",
            "rev": "2128d0aa28edef51fd8fef38b132ffc0155595df"
          },
          {
            "name": "nixos-unstable",
            "rev": "5aaed40d22f0d9376330b6fa413223435ad6fee5"
          }
        ],
        "score": 9.1,
        "description": "An issue was discovered in the DNS proxy in Connman through 1.40. forward_dns_reply mishandles a strnlen call, leading to an out-of-bounds read."
      },
      "CVE-2022-23096": {
        "branches": [
          {
            "name": "nixos-21.11",
            "rev": "2128d0aa28edef51fd8fef38b132ffc0155595df"
          },
          {
            "name": "nixos-unstable",
            "rev": "5aaed40d22f0d9376330b6fa413223435ad6fee5"
          }
        ],
        "score": 9.1,
        "description": "An issue was discovered in the DNS proxy in Connman through 1.40. The TCP server reply implementation lacks a check for the presence of sufficient Header Data, leading to an out-of-bounds read."
      }
    },
    "maintainers": [
      {
        "github": "matejc",
        "email": "cotman.matej@gmail.com"
      }
    ]
  },
  "issue_id": 160642,
  "issue_url": "https://api.github.com/repos/NixOS/nixpkgs/issues/160642"
}
